{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.promtail.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "grafana-loki.promtail.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: grafana-loki
    app.kubernetes.io/component: loki
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
stringData:
  promtail.yaml: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.promtail.configuration "context" $) | nindent 4 }}
{{- end }}
