---
apiVersion: v1
kind: Secret
metadata:
  name: loandb-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_PASSWORD: bG9hbnBhc3N3b3Jk

---

apiVersion: v1
kind: Secret
metadata:
  name: accountdb-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_PASSWORD: YWNjb3VudHBhc3N3b3Jk

---

apiVersion: v1
kind: Secret
metadata:
  name: carddb-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_PASSWORD: Y2FyZHBhc3N3b3Jk

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: loandb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/loandb-pv"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: accountdb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/accountdb-pv"

---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: card-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/carddb-pv"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loandb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accountdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carddb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loandb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loandb
  template:
    metadata:
      labels:
        app: loandb
    spec:
      containers:
      - name: loandb-container
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: loandb-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: loandb
        - name: MYSQL_USER
          value: loanuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: loandb-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: loandb-persistent-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: loandb-persistent-storage
        persistentVolumeClaim:
          claimName: loandb-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountdb
  template:
    metadata:
      labels:
        app: accountdb
    spec:
      containers:
      - name: accountdb-container
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: accountdb-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: accountdb
        - name: MYSQL_USER
          value: accountuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: accountdb-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: accountdb-persistent-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: accountdb-persistent-storage
        persistentVolumeClaim:
          claimName: accountdb-pvc


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: carddb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carddb
  template:
    metadata:
      labels:
        app: carddb
    spec:
      containers:
      - name: carddb-container
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: carddb-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: carddb
        - name: MYSQL_USER
          value: carduser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: carddb-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: carddb-persistent-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: carddb-persistent-storage
        persistentVolumeClaim:
          claimName: carddb-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: loandb-service
spec:
  selector:
    app: loandb
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3306
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: accountdb-service
spec:
  selector:
    app: accountdb
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3306
  type: ClusterIP


---

apiVersion: v1
kind: Service
metadata:
  name: carddb-service
spec:
  selector:
    app: carddb
  ports:
    - protocol: TCP
      port: 3309
      targetPort: 3306
  type: ClusterIP


