{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.imageRenderer.enabled  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-image-renderer
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: image-renderer
  annotations: 
    {{- if and .Values.imageRenderer.metrics.enabled .Values.imageRenderer.metrics.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.imageRenderer.metrics.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.imageRenderer.service.type }}
  {{- if and (eq .Values.imageRenderer.service.type "LoadBalancer") (not (empty .Values.imageRenderer.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.imageRenderer.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.imageRenderer.service.type "LoadBalancer") (not (empty .Values.imageRenderer.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.imageRenderer.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and .Values.imageRenderer.service.clusterIP (eq .Values.imageRenderer.service.type "ClusterIP") }}
  clusterIP: {{ .Values.imageRenderer.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.imageRenderer.service.type "LoadBalancer") (eq .Values.imageRenderer.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.imageRenderer.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if .Values.imageRenderer.service.sessionAffinity }}
  sessionAffinity: {{ .Values.imageRenderer.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.imageRenderer.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.imageRenderer.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.imageRenderer.service.ports.imageRenderer }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (or (eq .Values.imageRenderer.service.type "NodePort") (eq .Values.imageRenderer.service.type "LoadBalancer")) (not (empty .Values.imageRenderer.service.nodePorts.grafana)) }}
      nodePort: {{ .Values.imageRenderer.service.nodePorts.grafana }}
      {{- else if eq .Values.imageRenderer.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.imageRenderer.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.imageRenderer.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  {{- $podLabels := merge .Values.imageRenderer.podLabels .Values.commonLabels }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: image-renderer
{{- end }}
