{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.imageRenderer.metrics.enabled .Values.imageRenderer.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "common.names.fullname" . }}-image-renderer
  namespace: {{ default .Release.Namespace .Values.imageRenderer.metrics.serviceMonitor.namespace | quote }}
  {{- $labels := merge .Values.imageRenderer.metrics.serviceMonitor.labels .Values.commonLabels }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: image-renderer
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 6 }}
      {{- if .Values.imageRenderer.metrics.serviceMonitor.selector }}
      {{- include "common.tplvalues.render" (dict "value" .Values.imageRenderer.metrics.serviceMonitor.selector "context" $) | nindent 6 }}
      {{- end }}
      app.kubernetes.io/component: image-renderer
  endpoints:
    - port: http
      path: "/metrics"
      {{- if .Values.imageRenderer.metrics.serviceMonitor.interval }}
      interval: {{ .Values.imageRenderer.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.imageRenderer.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.imageRenderer.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.imageRenderer.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.imageRenderer.metrics.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.imageRenderer.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.imageRenderer.metrics.serviceMonitor.metricRelabelings "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.imageRenderer.metrics.serviceMonitor.relabelings }}
      relabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.imageRenderer.metrics.serviceMonitor.relabelings "context" $) | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
{{- end }}
